//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.11 at 04:22:04 PM BST 
//


package net.aconite.affina.espinterface.xmlmapping.cs;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.aconite.affina.espinterface.xmlmapping.cs package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.aconite.affina.espinterface.xmlmapping.cs
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NVPType }
     * 
     */
    public NVPType createNVPType() {
        return new NVPType();
    }

    /**
     * Create an instance of {@link SendScriptResponse }
     * 
     */
    public SendScriptResponse createSendScriptResponse() {
        return new SendScriptResponse();
    }

    /**
     * Create an instance of {@link TrackingReferenceType }
     * 
     */
    public TrackingReferenceType createTrackingReferenceType() {
        return new TrackingReferenceType();
    }

    /**
     * Create an instance of {@link UserType }
     * 
     */
    public UserType createUserType() {
        return new UserType();
    }

    /**
     * Create an instance of {@link SendScriptRequest }
     * 
     */
    public SendScriptRequest createSendScriptRequest() {
        return new SendScriptRequest();
    }

    /**
     * Create an instance of {@link BusFunctionType }
     * 
     */
    public BusFunctionType createBusFunctionType() {
        return new BusFunctionType();
    }

    /**
     * Create an instance of {@link DataContextType }
     * 
     */
    public DataContextType createDataContextType() {
        return new DataContextType();
    }

    /**
     * Create an instance of {@link RejectionType }
     * 
     */
    public RejectionType createRejectionType() {
        return new RejectionType();
    }

    /**
     * Create an instance of {@link SendScriptRequest.ScriptFunction }
     * 
     */
    public SendScriptRequest.ScriptFunction createSendScriptRequestScriptFunction() {
        return new SendScriptRequest.ScriptFunction();
    }

    /**
     * Create an instance of {@link SendScriptRequest.BusinessApplication }
     * 
     */
    public SendScriptRequest.BusinessApplication createSendScriptRequestBusinessApplication() {
        return new SendScriptRequest.BusinessApplication();
    }

    /**
     * Create an instance of {@link UserType.Role }
     * 
     */
    public UserType.Role createUserTypeRole() {
        return new UserType.Role();
    }

    /**
     * Create an instance of {@link BusFunctionsType }
     * 
     */
    public BusFunctionsType createBusFunctionsType() {
        return new BusFunctionsType();
    }

}
