//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.11 at 04:22:04 PM BST 
//


package net.aconite.affina.espinterface.xmlmapping.cs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TrackingReference" type="{}TrackingReferenceType"/>
 *         &lt;element name="Rejection" type="{}RejectionType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "trackingReference",
    "rejection"
})
@XmlRootElement(name = "SendScriptResponse")
public class SendScriptResponse {

    @XmlElement(name = "TrackingReference", required = true)
    protected TrackingReferenceType trackingReference;
    @XmlElement(name = "Rejection")
    protected RejectionType rejection;

    /**
     * Gets the value of the trackingReference property.
     * 
     * @return
     *     possible object is
     *     {@link TrackingReferenceType }
     *     
     */
    public TrackingReferenceType getTrackingReference() {
        return trackingReference;
    }

    /**
     * Sets the value of the trackingReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrackingReferenceType }
     *     
     */
    public void setTrackingReference(TrackingReferenceType value) {
        this.trackingReference = value;
    }

    /**
     * Gets the value of the rejection property.
     * 
     * @return
     *     possible object is
     *     {@link RejectionType }
     *     
     */
    public RejectionType getRejection() {
        return rejection;
    }

    /**
     * Sets the value of the rejection property.
     * 
     * @param value
     *     allowed object is
     *     {@link RejectionType }
     *     
     */
    public void setRejection(RejectionType value) {
        this.rejection = value;
    }

}
