//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.11 at 04:22:04 PM BST 
//


package net.aconite.affina.espinterface.xmlmapping.cs;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="User" type="{}UserType"/>
 *         &lt;element name="DataContext" type="{}DataContextType"/>
 *         &lt;element name="TrackingRef" type="{}ShortTrackingRefType"/>
 *         &lt;element name="CardId" type="{}CardIdType"/>
 *         &lt;element name="BusinessApplication">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ScriptStartDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="ScriptEndDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="ScriptFunction">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="Function" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Restage" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "user",
    "dataContext",
    "trackingRef",
    "cardId",
    "businessApplication",
    "scriptStartDate",
    "scriptEndDate",
    "scriptFunction",
    "restage"
})
@XmlRootElement(name = "SendScriptRequest")
public class SendScriptRequest {

    @XmlElement(name = "User", required = true)
    protected UserType user;
    @XmlElement(name = "DataContext", required = true)
    protected DataContextType dataContext;
    @XmlElement(name = "TrackingRef", required = true)
    protected String trackingRef;
    @XmlElement(name = "CardId", required = true)
    protected String cardId;
    @XmlElement(name = "BusinessApplication", required = true)
    protected SendScriptRequest.BusinessApplication businessApplication;
    @XmlElement(name = "ScriptStartDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar scriptStartDate;
    @XmlElement(name = "ScriptEndDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar scriptEndDate;
    @XmlElement(name = "ScriptFunction", required = true)
    protected SendScriptRequest.ScriptFunction scriptFunction;
    @XmlElement(name = "Restage")
    protected BigInteger restage;

    /**
     * Gets the value of the user property.
     * 
     * @return
     *     possible object is
     *     {@link UserType }
     *     
     */
    public UserType getUser() {
        return user;
    }

    /**
     * Sets the value of the user property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserType }
     *     
     */
    public void setUser(UserType value) {
        this.user = value;
    }

    /**
     * Gets the value of the dataContext property.
     * 
     * @return
     *     possible object is
     *     {@link DataContextType }
     *     
     */
    public DataContextType getDataContext() {
        return dataContext;
    }

    /**
     * Sets the value of the dataContext property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataContextType }
     *     
     */
    public void setDataContext(DataContextType value) {
        this.dataContext = value;
    }

    /**
     * Gets the value of the trackingRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrackingRef() {
        return trackingRef;
    }

    /**
     * Sets the value of the trackingRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrackingRef(String value) {
        this.trackingRef = value;
    }

    /**
     * Gets the value of the cardId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardId() {
        return cardId;
    }

    /**
     * Sets the value of the cardId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardId(String value) {
        this.cardId = value;
    }

    /**
     * Gets the value of the businessApplication property.
     * 
     * @return
     *     possible object is
     *     {@link SendScriptRequest.BusinessApplication }
     *     
     */
    public SendScriptRequest.BusinessApplication getBusinessApplication() {
        return businessApplication;
    }

    /**
     * Sets the value of the businessApplication property.
     * 
     * @param value
     *     allowed object is
     *     {@link SendScriptRequest.BusinessApplication }
     *     
     */
    public void setBusinessApplication(SendScriptRequest.BusinessApplication value) {
        this.businessApplication = value;
    }

    /**
     * Gets the value of the scriptStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getScriptStartDate() {
        return scriptStartDate;
    }

    /**
     * Sets the value of the scriptStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setScriptStartDate(XMLGregorianCalendar value) {
        this.scriptStartDate = value;
    }

    /**
     * Gets the value of the scriptEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getScriptEndDate() {
        return scriptEndDate;
    }

    /**
     * Sets the value of the scriptEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setScriptEndDate(XMLGregorianCalendar value) {
        this.scriptEndDate = value;
    }

    /**
     * Gets the value of the scriptFunction property.
     * 
     * @return
     *     possible object is
     *     {@link SendScriptRequest.ScriptFunction }
     *     
     */
    public SendScriptRequest.ScriptFunction getScriptFunction() {
        return scriptFunction;
    }

    /**
     * Sets the value of the scriptFunction property.
     * 
     * @param value
     *     allowed object is
     *     {@link SendScriptRequest.ScriptFunction }
     *     
     */
    public void setScriptFunction(SendScriptRequest.ScriptFunction value) {
        this.scriptFunction = value;
    }

    /**
     * Gets the value of the restage property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRestage() {
        return restage;
    }

    /**
     * Sets the value of the restage property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRestage(BigInteger value) {
        this.restage = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class BusinessApplication {

        @XmlAttribute(required = true)
        protected String id;

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="Function" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class ScriptFunction {

        @XmlAttribute(name = "Function", required = true)
        protected String function;

        /**
         * Gets the value of the function property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFunction() {
            return function;
        }

        /**
         * Sets the value of the function property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFunction(String value) {
            this.function = value;
        }

    }

}
